#!/bin/bash
if [[ "$#" -ne 2 ]]
then 
echo "Invalid amount of arguments!"
exit 0
fi 
files=$(find $1 -type f -name "*")
for file in $files
do
filename=${file##*/}
filetype=${filename##*.}
filename=${filename%.*}
if [ -f "${2}/${filename}.${filetype}" ]; 
then 
i=1
while [ -f "${2}/${filename}_${i}.${filetype}" ]; 
do 
let i+=1
done
cp $file ${2}/${filename}_${i}.${filetype}
else
cp $file ${2}/${filename}.${filetype}
fi
done
echo "Content has been copied successfully!"
